### ISSUE TITLE
tests: Add test vectors from Paul Miller's `noble-curves`

### ISSUE THREAD

**Issue by pmerkleplant** [verklegarden/crysol#23] opened 2024-06-27 17:16 UTC
Paul Miller's `noble-curves` project provides different test vectors `crysol` should test again:
- [secp256k1 ECDSA signatures vectors](https://github.com/paulmillr/noble-curves/blob/main/test/vectors/secp256k1/ecdsa.json)
- [secp256k1 Point validity and de/encoding vectors](https://github.com/paulmillr/noble-curves/blob/main/test/vectors/secp256k1/points.json)

Note that .json files should be used, which can be injected either via forge's `stdJson` library or simple shell script using `cast` to abi-encode the vectors.

**Comment by obatirou** [comment] 2024-10-10 22:09
Made the first part with https://github.com/verklegarden/crysol/pull/32 for secp256k1 Point validity and de/encoding vectors.
For ECDSA it will be in an other PR.
From my understanding: to use the verify function from the ECDSA library, one would need to do some processing on vector values as it uses a scalar as a privateKey. Hence, one would need to get the `SecretKey` from the scalar `d`. For that it would require to have access to `secretKeyFromUint` from `Secp256k1`.

**Comment by pmerkleplant** [comment] 2024-10-11 21:09
> it would require to have access to `secretKeyFromUint` from `Secp256k1`.

Feel free to import the `Secp256k1` library anywhere if necessary. 👍

**Comment by obatirou** [comment] 2024-10-27 22:50
After investigation, the encoding of nobles curves test vectors is different from Crysol / Ethereum.
The recovery bit is not serialized into the compact or der format (see [small comment in README.md](https://github.com/paulmillr/noble-curves/tree/main?tab=readme-ov-file#ecdsa-public-key-recovery--extra-entropy))
We can see that the signature from the test vectors are in compact format which is r and s packed only.
https://github.com/paulmillr/noble-curves/blob/1db569a52474ea94d6ec06fbe5321d17395ca255/test/secp256k1.test.js#L210

Hence: 
* For valid and invalid case `sign`, we could compare r and s from nobles cuves VS `sk.signRaw` but not sure this is relevant as it would only compare forge vs noble curves as the signature is done by the vm in `ECDSAOffchain`. They should be equal as they both use RFC6979 for deterministic ECDSA signatures.
* For invalid case `verify`, the public key is provided and crysol expose a `yparity` function so something could be baked to compare results. 

-> I will work on a PR for invalid case

**Comment by obatirou** [comment] 2024-11-01 10:54
Out of 2021 vectors, 3 do not lead the same Signature compared to foundry vm.sign for valid cases of nobles test vectors

```
// raw parsed signature //
0x7cb38cc5712e9e11a767615f6080dbc111c9cdd613eb98999fd92a86bafd45407923ca1f4d03471d2866f776ef8a6d3cac099b427331aeb245aa9dafeddcf115
  // signed ///
  r = 0x3f8fe493cf305a7f02b2d2c060ba66a8f7bd13a7a64d5200c0655ad069bd85b5
  s = 0x1cf94236c3857e33a1023a5216cbc81b1dc3adcc1c71f4212df1997ffdfb140a
  // expected ///
  r = 0x7cb38cc5712e9e11a767615f6080dbc111c9cdd613eb98999fd92a86bafd4540
  s = 0x7923ca1f4d03471d2866f776ef8a6d3cac099b427331aeb245aa9dafeddcf115

// raw parsed signature //
0xa7f83b5963eaf5332c633327cc967be8f4166d3f1e0b77f9761d8f4e42211e9a58aae31be1eb1e496923bbe8ca5e843cfb89f4d986d61d4edfd7d6fc3c9cf62c
  // signed ///
  r = 0x2d0b04a7560652f419e2542ea7d27f2c4afb0e111bb409cfe9f34b7ff7d33158
  s = 0x50118e90fcfe28abd0635a2e90f00db72bdbfcedbf56dad4049de85798031b38
  // expected ///
  r = 0xa7f83b5963eaf5332c633327cc967be8f4166d3f1e0b77f9761d8f4e42211e9a
  s = 0x58aae31be1eb1e496923bbe8ca5e843cfb89f4d986d61d4edfd7d6fc3c9cf62c

// raw parsed signature //
0x919026f3e239ea52cf530eb6d345dc2b56ef0928f1e9ad20d8f360284dc6504814395e7137e2204f15b69239010f3c34fbb3c858a29b0d106b1fa65bc0047263
  // signed ///
  r = 0xccedf9058419be4bf0d0aaf55b20072bcf6acb16621ac4ab90a3ed20b83a85ce
  s = 0x6c2444f18d6069e828b3ce0e4e5f2f20a2d7e701042bb4bf9361b228f0091ac6
  // expected ///
  r = 0x919026f3e239ea52cf530eb6d345dc2b56ef0928f1e9ad20d8f360284dc65048
  s = 0x14395e7137e2204f15b69239010f3c34fbb3c858a29b0d106b1fa65bc0047263


Number of valid signatures:  2019
Invalid signatures:  3
  ```
  
This should not happen as foundry and nobles curves use RFC6979.
My investigation lead me to into looking at how k is generated for both repo:
* nobles-curves:  https://github.com/paulmillr/noble-curves/blob/1db569a52474ea94d6ec06fbe5321d17395ca255/src/abstract/weierstrass.ts#L1064
* Foundry depends on ECDSA 0.16.9 which depends on crate RFC6979 0.4.0 : 
    * https://github.com/foundry-rs/foundry/blob/6b0c27ed4ccfdb5a4805e9f53d487cca51c5e116/Cargo.lock#L2887
    * https://docs.rs/rfc6979/latest/rfc6979/fn.generate_k.html
    
I am still looking into it as I did not found the root cause yet.
    
Here the branch with the tests that lead to this 
https://github.com/verklegarden/crysol/compare/main...obatirou:crysol:nobles-curves-ecdsa

**Closed** 2024-12-05 17:09 UTC
Labels: good first issue, effort: low
